name: Docker Image Production

on:
  push:
    branches: [main]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Ensure Docker is installed
        run: docker --version

      - name: Set Docker image tag
        run: echo "TAG=v1.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build Docker image with tags
        run: |
          docker build -t chantip/472-s-golden-pillow-frontend-6510405369:latest \
                 -t chantip/472-s-golden-pillow-frontend-6510405369:${{ env.TAG }} .

      - name: Push Docker images
        run: |
          docker push chantip/472-s-golden-pillow-frontend-6510405369:latest
          docker push chantip/472-s-golden-pillow-frontend-6510405369:${{ env.TAG }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG }}
          name: Release ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
